name: android_ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: set up Java
      uses: actions/setup-java@v4
      with:
        java-version: '8.0.402+6'
        distribution: 'zulu'

    - uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 6.5

    - name: Print gradle version
      run: gradle --version

    - name: Building project
      run: gradle build

    - name: Testing project
      run: gradle test
