name: android_ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: set up Java
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'zulu'

    - name: Get google java format
      run: |
        wget https://github.com/google/google-java-format/releases/download/v1.23.0/google-java-format-1.23.0.jar


  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 17

    - uses: gradle/actions/setup-gradle
      with:
        gradle-version: '7.6.3'

    - name: Print gradle version
      run: gradle --version

    - name: Building project
      run: gradle build --no-daemon

    - name: Testing project
      run: gradle test

    - name: Google Java Format
      uses: axel-op/googlejavaformat-action@v4
      with:
        args: "--set-exit-if-changed"

  build-with-nix-shell:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install Nix
      uses: cachix/install-nix-action@v16
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - name: Activate Nix flake
      run: nix develop .

    - name: Build the project
      run: echo "TODO"
